[2023-11-15T03:57:32.286+0000] {processor.py:157} INFO - Started process (PID=34) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:57:32.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T03:57:32.294+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:57:32.293+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:57:33.443+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:57:33.460+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 1.180 seconds
[2023-11-15T03:58:03.640+0000] {processor.py:157} INFO - Started process (PID=92) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:03.644+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T03:58:03.649+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:03.649+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:04.139+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:04.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.522 seconds
[2023-11-15T03:58:14.739+0000] {processor.py:157} INFO - Started process (PID=150) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:14.740+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T03:58:14.743+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:14.742+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:15.245+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:15.358+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:15.357+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T03:58:15.369+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:15.369+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T03:58:15.395+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.659 seconds
[2023-11-15T03:58:45.810+0000] {processor.py:157} INFO - Started process (PID=208) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:45.813+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T03:58:45.817+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:45.816+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:46.661+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:46.681+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:46.681+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T03:58:46.694+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:46.694+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T03:58:46.719+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.916 seconds
[2023-11-15T03:58:57.359+0000] {processor.py:157} INFO - Started process (PID=210) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:57.361+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T03:58:57.373+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:57.372+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:58.077+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:58:58.101+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:58.100+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T03:58:58.114+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:58:58.114+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T03:58:58.140+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.792 seconds
[2023-11-15T03:59:05.170+0000] {processor.py:157} INFO - Started process (PID=215) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:05.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T03:59:05.174+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:05.174+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:05.931+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:05.955+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:05.955+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T03:59:05.969+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:05.969+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T03:59:05.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.829 seconds
[2023-11-15T03:59:36.881+0000] {processor.py:157} INFO - Started process (PID=277) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:36.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T03:59:36.887+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:36.887+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:37.552+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:37.669+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:37.668+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T03:59:37.682+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:37.682+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T03:59:37.704+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.828 seconds
[2023-11-15T03:59:40.592+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:40.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T03:59:40.596+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:40.596+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:41.326+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T03:59:41.341+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:41.340+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T03:59:41.357+0000] {logging_mixin.py:151} INFO - [2023-11-15T03:59:41.357+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T03:59:41.386+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.798 seconds
[2023-11-15T04:00:12.095+0000] {processor.py:157} INFO - Started process (PID=377) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:00:12.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:00:12.102+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:00:12.101+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:00:12.752+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:00:12.765+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:00:12.764+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:00:12.778+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:00:12.778+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:00:12.800+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.713 seconds
[2023-11-15T04:00:42.881+0000] {processor.py:157} INFO - Started process (PID=436) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:00:42.884+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:00:42.889+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:00:42.888+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:00:43.503+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:00:43.610+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:00:43.610+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:00:43.622+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:00:43.621+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:00:43.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.770 seconds
[2023-11-15T04:01:14.416+0000] {processor.py:157} INFO - Started process (PID=494) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:14.418+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:01:14.421+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:14.421+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:15.056+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:15.079+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:15.078+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:01:15.092+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:15.092+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:01:15.116+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.706 seconds
[2023-11-15T04:01:45.663+0000] {processor.py:157} INFO - Started process (PID=560) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:45.665+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:01:45.668+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:45.667+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:46.272+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:46.286+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:46.285+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:01:46.303+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:46.302+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:01:46.329+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.670 seconds
[2023-11-15T04:01:50.289+0000] {processor.py:157} INFO - Started process (PID=564) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:50.290+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:01:50.293+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:50.292+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:50.989+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:01:51.004+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:51.003+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:01:51.024+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:01:51.023+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:01:51.055+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.772 seconds
[2023-11-15T04:02:00.495+0000] {processor.py:157} INFO - Started process (PID=566) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:00.497+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:02:00.503+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:02:00.502+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:01.080+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:01.093+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:02:01.093+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:02:01.107+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:02:01.107+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:02:01.132+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.649 seconds
[2023-11-15T04:02:26.201+0000] {processor.py:157} INFO - Started process (PID=624) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:26.203+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:02:26.206+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:02:26.206+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:26.767+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:02:26.763+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 30, in <module>
    s3 = boto3.client('s3', aws_access_key_id=aws_access_key, aws_secret_access_key=aws_secret_key)
NameError: name 'aws_access_key' is not defined
[2023-11-15T04:02:26.767+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:26.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.595 seconds
[2023-11-15T04:02:40.462+0000] {processor.py:157} INFO - Started process (PID=633) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:40.463+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:02:40.466+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:02:40.465+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:41.742+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:02:41.897+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:02:41.896+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:02:41.914+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:02:41.914+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:02:41.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 1.487 seconds
[2023-11-15T04:03:12.962+0000] {processor.py:157} INFO - Started process (PID=693) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:12.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:03:12.969+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:12.969+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:13.778+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:13.800+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:13.799+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:03:13.819+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:13.819+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:03:13.841+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.885 seconds
[2023-11-15T04:03:43.997+0000] {processor.py:157} INFO - Started process (PID=756) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:43.998+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:03:44.001+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:44.000+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:44.884+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:45.034+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:45.033+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:03:45.047+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:45.047+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:03:45.076+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 1.083 seconds
[2023-11-15T04:03:49.067+0000] {processor.py:157} INFO - Started process (PID=800) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:49.068+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:03:49.073+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:49.073+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:49.804+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:03:49.818+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:49.818+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:03:49.837+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:03:49.836+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:03:49.864+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.803 seconds
[2023-11-15T04:04:20.337+0000] {processor.py:157} INFO - Started process (PID=860) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:04:20.340+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:04:20.342+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:04:20.342+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:04:21.049+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:04:21.062+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:04:21.061+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:04:21.076+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:04:21.076+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:04:21.104+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.771 seconds
[2023-11-15T04:04:51.346+0000] {processor.py:157} INFO - Started process (PID=918) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:04:51.347+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:04:51.350+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:04:51.350+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:04:52.159+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:04:52.287+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:04:52.286+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:04:52.305+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:04:52.305+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:04:52.332+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.989 seconds
[2023-11-15T04:05:22.924+0000] {processor.py:157} INFO - Started process (PID=977) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:05:22.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:05:22.928+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:05:22.928+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:05:23.675+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:05:23.742+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:05:23.741+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:05:23.756+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:05:23.756+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:05:23.783+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.863 seconds
[2023-11-15T04:05:53.989+0000] {processor.py:157} INFO - Started process (PID=1036) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:05:53.990+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:05:53.993+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:05:53.992+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:05:54.711+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:05:54.723+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:05:54.723+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:05:54.737+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:05:54.737+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:05:54.760+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.775 seconds
[2023-11-15T04:06:24.920+0000] {processor.py:157} INFO - Started process (PID=1093) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:06:24.922+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:06:24.927+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:06:24.926+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:06:25.804+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:06:25.924+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:06:25.923+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:06:25.937+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:06:25.936+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:06:25.962+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 1.052 seconds
[2023-11-15T04:06:56.009+0000] {processor.py:157} INFO - Started process (PID=1151) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:06:56.011+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:06:56.014+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:06:56.014+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:06:56.787+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:06:56.812+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:06:56.811+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:06:56.832+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:06:56.832+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:06:56.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.855 seconds
[2023-11-15T04:07:14.260+0000] {processor.py:157} INFO - Started process (PID=1162) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:07:14.262+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:07:14.265+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:07:14.265+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:07:14.270+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:07:14.269+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 79
    s3.upload_file(, bucket_name, s3_file_path)
                   ^
SyntaxError: invalid syntax
[2023-11-15T04:07:14.270+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:07:14.295+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.041 seconds
[2023-11-15T04:07:44.706+0000] {processor.py:157} INFO - Started process (PID=1219) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:07:44.708+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:07:44.711+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:07:44.711+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:07:44.715+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:07:44.714+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 79
    s3.upload_file(, bucket_name, s3_file_path)
                   ^
SyntaxError: invalid syntax
[2023-11-15T04:07:44.715+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:07:44.741+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.042 seconds
[2023-11-15T04:08:14.914+0000] {processor.py:157} INFO - Started process (PID=1276) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:14.915+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:08:14.917+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:08:14.917+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:14.920+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:08:14.920+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 79
    s3.upload_file(, bucket_name, s3_file_path)
                   ^
SyntaxError: invalid syntax
[2023-11-15T04:08:14.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:14.944+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.034 seconds
[2023-11-15T04:08:18.089+0000] {processor.py:157} INFO - Started process (PID=1286) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:18.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:08:18.094+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:08:18.094+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:18.097+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:08:18.097+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 81
    s3.upload_file(, bucket_name, s3_file_path)
                   ^
SyntaxError: invalid syntax
[2023-11-15T04:08:18.098+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:18.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.034 seconds
[2023-11-15T04:08:48.489+0000] {processor.py:157} INFO - Started process (PID=1343) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:48.490+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:08:48.493+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:08:48.493+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:48.497+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:08:48.496+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 81
    s3.upload_file(, bucket_name, s3_file_path)
                   ^
SyntaxError: invalid syntax
[2023-11-15T04:08:48.497+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:08:48.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.036 seconds
[2023-11-15T04:09:19.230+0000] {processor.py:157} INFO - Started process (PID=1400) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:09:19.235+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:09:19.238+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:09:19.238+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:09:19.242+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:09:19.241+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 81
    s3.upload_file(, bucket_name, s3_file_path)
                   ^
SyntaxError: invalid syntax
[2023-11-15T04:09:19.243+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:09:19.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.053 seconds
[2023-11-15T04:09:49.484+0000] {processor.py:157} INFO - Started process (PID=1457) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:09:49.485+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:09:49.488+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:09:49.488+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:09:49.492+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:09:49.491+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 81
    s3.upload_file(, bucket_name, s3_file_path)
                   ^
SyntaxError: invalid syntax
[2023-11-15T04:09:49.492+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:09:49.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.038 seconds
[2023-11-15T04:10:20.020+0000] {processor.py:157} INFO - Started process (PID=1514) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:20.024+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:10:20.030+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:10:20.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:20.035+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:10:20.033+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 81
    s3.upload_file(, bucket_name, s3_file_path)
                   ^
SyntaxError: invalid syntax
[2023-11-15T04:10:20.036+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:20.074+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.060 seconds
[2023-11-15T04:10:34.137+0000] {processor.py:157} INFO - Started process (PID=1555) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:34.138+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:10:34.143+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:10:34.142+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:34.149+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:10:34.148+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 81
    s3.put_object(Body=csv_buffer.getvalue(), Bucket=BUCKET_NAME, Key=)
                                                                      ^
SyntaxError: invalid syntax
[2023-11-15T04:10:34.150+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:34.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.046 seconds
[2023-11-15T04:10:48.867+0000] {processor.py:157} INFO - Started process (PID=1572) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:48.870+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:10:48.880+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:10:48.879+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:48.888+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:10:48.886+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 81
    s3.put_object(Body=csv_buffer.getvalue(), Bucket=BUCKET_NAME, Key=)
                                                                      ^
SyntaxError: invalid syntax
[2023-11-15T04:10:48.889+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:48.924+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.072 seconds
[2023-11-15T04:10:57.465+0000] {processor.py:157} INFO - Started process (PID=1609) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:57.469+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:10:57.472+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:10:57.471+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:57.475+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:10:57.474+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 81
    s3.put_object(Body=csv_buffer.getvalue(), Bucket=BUCKET_NAME, Key=)
                                                                      ^
SyntaxError: invalid syntax
[2023-11-15T04:10:57.475+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:10:57.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.039 seconds
[2023-11-15T04:11:05.619+0000] {processor.py:157} INFO - Started process (PID=1614) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:05.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:11:05.625+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:05.624+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:06.319+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:06.437+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:06.436+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:11:06.449+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:06.449+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:11:06.477+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.869 seconds
[2023-11-15T04:11:13.306+0000] {processor.py:157} INFO - Started process (PID=1616) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:13.307+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:11:13.309+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:13.309+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:14.040+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:14.053+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:14.052+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:11:14.068+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:14.068+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:11:14.096+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.796 seconds
[2023-11-15T04:11:44.150+0000] {processor.py:157} INFO - Started process (PID=1674) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:44.152+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:11:44.155+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:44.155+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:44.827+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:44.849+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:44.848+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:11:44.866+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:44.865+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:11:44.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.744 seconds
[2023-11-15T04:11:52.893+0000] {processor.py:157} INFO - Started process (PID=1693) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:52.894+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:11:52.896+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:52.896+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:53.611+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:53.632+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:53.631+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:11:53.645+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:53.644+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:11:53.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.783 seconds
[2023-11-15T04:11:53.838+0000] {processor.py:157} INFO - Started process (PID=1701) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:53.839+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:11:53.842+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:53.841+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:54.611+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:11:54.630+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:54.630+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:11:54.646+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:11:54.645+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:11:54.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.838 seconds
[2023-11-15T04:12:18.062+0000] {processor.py:157} INFO - Started process (PID=1743) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:18.064+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:12:18.067+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:18.067+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:18.804+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:18.818+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:18.817+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:12:18.836+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:18.836+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:12:18.867+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.811 seconds
[2023-11-15T04:12:24.526+0000] {processor.py:157} INFO - Started process (PID=1759) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:24.528+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:12:24.532+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:24.531+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:25.283+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:25.295+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:25.294+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:12:25.309+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:25.309+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:12:25.336+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.815 seconds
[2023-11-15T04:12:33.965+0000] {processor.py:157} INFO - Started process (PID=1794) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:33.965+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:12:33.968+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:33.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:34.847+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:34.970+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:34.969+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:12:34.985+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:34.984+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:12:35.152+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 1.191 seconds
[2023-11-15T04:12:43.634+0000] {processor.py:157} INFO - Started process (PID=1798) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:43.635+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:12:43.639+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:43.639+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:44.315+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:12:44.329+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:44.328+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:12:44.345+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:12:44.345+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:12:44.373+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.745 seconds
[2023-11-15T04:13:04.343+0000] {processor.py:157} INFO - Started process (PID=1852) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:04.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:13:04.348+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:04.347+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:04.352+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:04.351+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 117
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:13:04.352+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:04.376+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.037 seconds
[2023-11-15T04:13:06.096+0000] {processor.py:157} INFO - Started process (PID=1855) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:06.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:13:06.102+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:06.102+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:06.109+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:06.108+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 117
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:13:06.110+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:06.139+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.051 seconds
[2023-11-15T04:13:07.113+0000] {processor.py:157} INFO - Started process (PID=1856) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:07.114+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:13:07.117+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:07.117+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:07.122+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:07.121+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 117
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:13:07.122+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:07.149+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.041 seconds
[2023-11-15T04:13:13.206+0000] {processor.py:157} INFO - Started process (PID=1859) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:13.207+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:13:13.209+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:13.209+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:13.214+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:13.212+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 117
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:13:13.214+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:13.238+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.036 seconds
[2023-11-15T04:13:18.279+0000] {processor.py:157} INFO - Started process (PID=1860) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:18.280+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:13:18.286+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:18.285+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:18.292+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:18.290+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 119
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:13:18.292+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:18.317+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.045 seconds
[2023-11-15T04:13:21.174+0000] {processor.py:157} INFO - Started process (PID=1877) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:21.175+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:13:21.179+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:21.179+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:21.183+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:21.182+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 119
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:13:21.183+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:21.208+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.042 seconds
[2023-11-15T04:13:51.573+0000] {processor.py:157} INFO - Started process (PID=1934) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:51.575+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:13:51.578+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:51.578+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:51.582+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:13:51.581+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 119
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:13:51.583+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:13:51.606+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.037 seconds
[2023-11-15T04:14:22.258+0000] {processor.py:157} INFO - Started process (PID=1991) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:14:22.259+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:14:22.261+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:14:22.261+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:14:22.265+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:14:22.264+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 119
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:14:22.266+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:14:22.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.037 seconds
[2023-11-15T04:14:33.694+0000] {processor.py:157} INFO - Started process (PID=2028) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:14:33.696+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:14:33.700+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:14:33.699+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:14:33.705+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:14:33.704+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 118
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:14:33.706+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:14:33.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.045 seconds
[2023-11-15T04:15:04.284+0000] {processor.py:157} INFO - Started process (PID=2085) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:04.286+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:15:04.290+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:15:04.289+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:04.294+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:15:04.293+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 118
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:15:04.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:04.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.049 seconds
[2023-11-15T04:15:34.541+0000] {processor.py:157} INFO - Started process (PID=2143) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:34.547+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:15:34.552+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:15:34.551+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:34.558+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:15:34.557+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 118
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:15:34.559+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:34.582+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.049 seconds
[2023-11-15T04:15:36.594+0000] {processor.py:157} INFO - Started process (PID=2144) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:36.596+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:15:36.599+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:15:36.598+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:36.603+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:15:36.602+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 127
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:15:36.603+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:36.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.042 seconds
[2023-11-15T04:15:47.840+0000] {processor.py:157} INFO - Started process (PID=2149) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:47.841+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:15:47.844+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:15:47.843+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:47.848+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:15:47.847+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 127
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:15:47.849+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:15:47.915+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.080 seconds
[2023-11-15T04:16:01.987+0000] {processor.py:157} INFO - Started process (PID=2188) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:01.988+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:16:01.990+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:16:01.990+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:01.995+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:16:01.993+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 127
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:16:01.995+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:02.020+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.037 seconds
[2023-11-15T04:16:27.546+0000] {processor.py:157} INFO - Started process (PID=2224) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:27.549+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:16:27.553+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:16:27.552+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:27.559+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:16:27.557+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 127
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:16:27.559+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:27.585+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.045 seconds
[2023-11-15T04:16:28.873+0000] {processor.py:157} INFO - Started process (PID=2229) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:28.875+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:16:28.880+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:16:28.879+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:28.887+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:16:28.885+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 127
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:16:28.888+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:28.910+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.044 seconds
[2023-11-15T04:16:36.106+0000] {processor.py:157} INFO - Started process (PID=2261) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:36.108+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:16:36.113+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:16:36.112+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:36.119+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:16:36.118+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 129
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:16:36.120+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:16:36.145+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.047 seconds
[2023-11-15T04:17:06.388+0000] {processor.py:157} INFO - Started process (PID=2318) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:06.390+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:17:06.393+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:17:06.392+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:06.396+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:17:06.395+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 129
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:17:06.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:06.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.036 seconds
[2023-11-15T04:17:34.088+0000] {processor.py:157} INFO - Started process (PID=2360) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:34.089+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:17:34.091+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:17:34.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:34.095+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:17:34.094+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 135
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:17:34.096+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:34.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.035 seconds
[2023-11-15T04:17:55.941+0000] {processor.py:157} INFO - Started process (PID=2394) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:55.943+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:17:55.947+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:17:55.947+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:55.953+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:17:55.952+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 135
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:17:55.953+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:17:55.976+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.040 seconds
[2023-11-15T04:18:14.547+0000] {processor.py:157} INFO - Started process (PID=2433) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:14.548+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:18:14.554+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:18:14.553+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:14.558+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:18:14.557+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 134
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:18:14.558+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:14.583+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.043 seconds
[2023-11-15T04:18:36.856+0000] {processor.py:157} INFO - Started process (PID=2490) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:36.858+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:18:36.862+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:18:36.862+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:36.868+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:18:36.866+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 134
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:18:36.868+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:36.896+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.051 seconds
[2023-11-15T04:18:42.965+0000] {processor.py:157} INFO - Started process (PID=2491) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:42.968+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:18:42.978+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:18:42.977+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:42.984+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:18:42.982+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 133
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:18:42.984+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:18:43.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.072 seconds
[2023-11-15T04:19:02.435+0000] {processor.py:157} INFO - Started process (PID=2521) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:02.436+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:19:02.438+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:02.438+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:02.442+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:02.441+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/recalls_etl_s3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/recalls_etl_s3.py", line 133
    'raw_output_path': raw_data_path
    ^
SyntaxError: invalid syntax
[2023-11-15T04:19:02.442+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:02.465+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.036 seconds
[2023-11-15T04:19:21.056+0000] {processor.py:157} INFO - Started process (PID=2560) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:21.061+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:19:21.065+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:21.065+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:21.489+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:21.624+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:21.622+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:19:21.652+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:21.651+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:19:21.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.651 seconds
[2023-11-15T04:19:26.806+0000] {processor.py:157} INFO - Started process (PID=2563) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:26.807+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:19:26.810+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:26.809+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:27.250+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:27.263+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:27.262+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:19:27.279+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:27.279+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:19:27.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.510 seconds
[2023-11-15T04:19:48.913+0000] {processor.py:157} INFO - Started process (PID=2609) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:48.914+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:19:48.917+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:48.916+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:49.371+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:19:49.388+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:49.388+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:19:49.408+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:19:49.408+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:19:49.440+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.537 seconds
[2023-11-15T04:20:00.924+0000] {processor.py:157} INFO - Started process (PID=2632) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:00.925+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:20:00.927+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:00.927+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:01.329+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:01.455+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:01.454+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:20:01.471+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:01.470+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:20:01.500+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.581 seconds
[2023-11-15T04:20:08.245+0000] {processor.py:157} INFO - Started process (PID=2669) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:08.246+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:20:08.249+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:08.248+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:08.732+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:08.747+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:08.746+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:20:08.763+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:08.763+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:20:08.791+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.550 seconds
[2023-11-15T04:20:23.377+0000] {processor.py:157} INFO - Started process (PID=2682) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:23.378+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:20:23.381+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:23.381+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:23.804+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:23.819+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:23.818+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:20:23.835+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:23.835+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:20:23.863+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.489 seconds
[2023-11-15T04:20:46.096+0000] {processor.py:157} INFO - Started process (PID=2729) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:46.098+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:20:46.101+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:46.101+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:46.525+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:46.549+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:46.548+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:20:46.566+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:46.566+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:20:46.594+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.505 seconds
[2023-11-15T04:20:51.196+0000] {processor.py:157} INFO - Started process (PID=2740) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:51.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:20:51.200+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:51.199+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:51.624+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:51.640+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:51.639+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:20:51.657+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:51.656+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:20:51.684+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.492 seconds
[2023-11-15T04:20:56.733+0000] {processor.py:157} INFO - Started process (PID=2744) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:56.734+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:20:56.737+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:56.736+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:57.190+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:57.205+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:57.204+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:20:57.219+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:57.219+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:20:57.241+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.512 seconds
[2023-11-15T04:20:59.756+0000] {processor.py:157} INFO - Started process (PID=2755) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:20:59.757+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:20:59.761+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:20:59.761+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:00.189+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:00.202+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:00.202+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:21:00.217+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:00.217+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:21:00.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.489 seconds
[2023-11-15T04:21:16.492+0000] {processor.py:157} INFO - Started process (PID=2793) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:16.493+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:21:16.497+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:16.496+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:16.914+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:16.929+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:16.928+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:21:16.946+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:16.946+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:21:16.971+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.485 seconds
[2023-11-15T04:21:22.035+0000] {processor.py:157} INFO - Started process (PID=2804) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:22.037+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:21:22.040+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:22.040+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:22.498+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:22.621+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:22.620+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:21:22.634+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:22.633+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:21:22.659+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.629 seconds
[2023-11-15T04:21:53.034+0000] {processor.py:157} INFO - Started process (PID=2861) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:53.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:21:53.040+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:53.039+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:53.591+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:53.633+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:53.632+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:21:53.658+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:53.658+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:21:53.692+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.664 seconds
[2023-11-15T04:21:57.117+0000] {processor.py:157} INFO - Started process (PID=2867) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:57.118+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:21:57.122+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:57.121+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:57.613+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:21:57.628+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:57.627+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:21:57.644+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:21:57.644+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:21:57.674+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.564 seconds
[2023-11-15T04:22:22.759+0000] {processor.py:157} INFO - Started process (PID=2921) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:22.760+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:22:22.762+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:22.762+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:23.217+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:23.231+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:23.230+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:22:23.246+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:23.246+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:22:23.277+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.522 seconds
[2023-11-15T04:22:32.392+0000] {processor.py:157} INFO - Started process (PID=2936) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:32.394+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:22:32.398+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:32.397+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:32.837+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:32.953+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:32.952+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:22:32.967+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:32.966+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:22:32.994+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.607 seconds
[2023-11-15T04:22:41.658+0000] {processor.py:157} INFO - Started process (PID=2974) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:41.658+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:22:41.661+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:41.660+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:42.202+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:22:42.216+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:42.216+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:22:42.231+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:22:42.231+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:22:42.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.601 seconds
[2023-11-15T04:23:02.737+0000] {processor.py:157} INFO - Started process (PID=2995) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:02.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:23:02.744+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:02.743+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:03.202+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:03.228+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:03.227+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:23:03.247+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:03.247+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:23:03.279+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.552 seconds
[2023-11-15T04:23:07.343+0000] {processor.py:157} INFO - Started process (PID=3010) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:07.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:23:07.347+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:07.347+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:07.772+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:07.797+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:07.796+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:23:07.812+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:07.812+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:23:07.842+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.503 seconds
[2023-11-15T04:23:37.881+0000] {processor.py:157} INFO - Started process (PID=3064) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:37.882+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:23:37.886+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:37.885+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:38.356+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:23:38.370+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:38.369+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:23:38.386+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:23:38.386+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:23:38.415+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.539 seconds
[2023-11-15T04:24:09.047+0000] {processor.py:157} INFO - Started process (PID=3122) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:24:09.050+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:24:09.054+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:24:09.054+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:24:09.465+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:24:09.585+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:24:09.584+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:24:09.600+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:24:09.600+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:24:09.629+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.591 seconds
[2023-11-15T04:24:40.227+0000] {processor.py:157} INFO - Started process (PID=3180) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:24:40.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:24:40.233+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:24:40.232+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:24:40.842+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:24:40.871+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:24:40.870+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:24:40.895+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:24:40.894+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:24:40.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.707 seconds
[2023-11-15T04:25:11.043+0000] {processor.py:157} INFO - Started process (PID=3239) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:11.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:25:11.046+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:11.046+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:11.467+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_v1']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:11.480+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:11.480+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:25:11.495+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:11.495+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_v1 to None, run_after=None
[2023-11-15T04:25:11.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.479 seconds
[2023-11-15T04:25:31.661+0000] {processor.py:157} INFO - Started process (PID=3279) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:31.663+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:25:31.666+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:31.665+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:32.086+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_s3']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:32.323+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:32.323+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-15T04:25:32.352+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:32.351+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-15T04:25:32.367+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:32.366+0000] {manager.py:499} INFO - Created Permission View: %s
[2023-11-15T04:25:32.369+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:32.368+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:25:32.390+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:32.389+0000] {dag.py:2963} INFO - Creating ORM DAG for recalls_etl_s3
[2023-11-15T04:25:32.391+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:32.391+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_s3 to None, run_after=None
[2023-11-15T04:25:32.416+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.761 seconds
[2023-11-15T04:25:39.749+0000] {processor.py:157} INFO - Started process (PID=3298) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:39.750+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:25:39.755+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:39.754+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:40.344+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_s3']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:25:40.362+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:40.362+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:25:40.379+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:25:40.378+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_s3 to None, run_after=None
[2023-11-15T04:25:40.417+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.678 seconds
[2023-11-15T04:26:11.047+0000] {processor.py:157} INFO - Started process (PID=3356) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:11.049+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:26:11.052+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:11.052+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:11.483+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_s3']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:11.506+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:11.505+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:26:11.524+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:11.523+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_s3 to None, run_after=None
[2023-11-15T04:26:11.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.506 seconds
[2023-11-15T04:26:41.739+0000] {processor.py:157} INFO - Started process (PID=3414) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:41.741+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:26:41.744+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:41.743+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:42.346+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_s3']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:42.383+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:42.381+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:26:42.410+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:42.410+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_s3 to None, run_after=None
[2023-11-15T04:26:42.449+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.715 seconds
[2023-11-15T04:26:55.230+0000] {processor.py:157} INFO - Started process (PID=3450) to work on /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:55.233+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/recalls_etl_s3.py for tasks to queue
[2023-11-15T04:26:55.237+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:55.237+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:55.635+0000] {processor.py:839} INFO - DAG(s) dict_keys(['recalls_etl_s3']) retrieved from /opt/airflow/dags/recalls_etl_s3.py
[2023-11-15T04:26:55.660+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:55.659+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-11-15T04:26:55.674+0000] {logging_mixin.py:151} INFO - [2023-11-15T04:26:55.674+0000] {dag.py:3722} INFO - Setting next_dagrun for recalls_etl_s3 to None, run_after=None
[2023-11-15T04:26:55.702+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/recalls_etl_s3.py took 0.480 seconds
