[2023-11-04T03:39:38.212+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2023-11-04T03:39:28.790160+00:00 [queued]>
[2023-11-04T03:39:38.224+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2023-11-04T03:39:28.790160+00:00 [queued]>
[2023-11-04T03:39:38.224+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-04T03:39:38.242+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_to_db> on 2023-11-04 03:39:28.790160+00:00
[2023-11-04T03:39:38.248+0000] {standard_task_runner.py:57} INFO - Started process 255 to run task
[2023-11-04T03:39:38.252+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'load_data_to_db', 'manual__2023-11-04T03:39:28.790160+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpkbzxfqf8']
[2023-11-04T03:39:38.253+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask load_data_to_db
[2023-11-04T03:39:38.308+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_v1.load_data_to_db manual__2023-11-04T03:39:28.790160+00:00 [running]> on host d2f41c2a3488
[2023-11-04T03:39:38.403+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='load_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-11-04T03:39:28.790160+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-04T03:39:28.790160+00:00'
[2023-11-04T03:39:39.843+0000] {logging_mixin.py:151} INFO - Success: Loaded 29201 recall records to recalls_db.
[2023-11-04T03:39:39.845+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-04T03:39:39.857+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=recalls_etl_v1, task_id=load_data_to_db, execution_date=20231104T033928, start_date=20231104T033938, end_date=20231104T033939
[2023-11-04T03:39:39.910+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-04T03:39:39.931+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
