[2023-11-15T04:25:54.960+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_s3.load_data_to_db manual__2023-11-15T04:25:41.907414+00:00 [queued]>
[2023-11-15T04:25:54.972+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_s3.load_data_to_db manual__2023-11-15T04:25:41.907414+00:00 [queued]>
[2023-11-15T04:25:54.972+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-11-15T04:25:54.990+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_to_db> on 2023-11-15 04:25:41.907414+00:00
[2023-11-15T04:25:54.996+0000] {standard_task_runner.py:57} INFO - Started process 476 to run task
[2023-11-15T04:25:55.000+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_s3', 'load_data_to_db', 'manual__2023-11-15T04:25:41.907414+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_s3.py', '--cfg-path', '/tmp/tmpbz5kue3k']
[2023-11-15T04:25:55.002+0000] {standard_task_runner.py:85} INFO - Job 57: Subtask load_data_to_db
[2023-11-15T04:25:55.060+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_s3.load_data_to_db manual__2023-11-15T04:25:41.907414+00:00 [running]> on host c912e3390c69
[2023-11-15T04:25:55.240+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_s3' AIRFLOW_CTX_TASK_ID='load_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2023-11-15T04:25:41.907414+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-15T04:25:41.907414+00:00'
[2023-11-15T04:25:57.813+0000] {logging_mixin.py:151} INFO - Success: Loaded 29270 recall records to recalls_db.
[2023-11-15T04:25:57.817+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-15T04:25:57.830+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=recalls_etl_s3, task_id=load_data_to_db, execution_date=20231115T042541, start_date=20231115T042554, end_date=20231115T042557
[2023-11-15T04:25:57.863+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-15T04:25:57.883+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
